### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by msprosser** [msprosser/rpg#1]
After latest changes, the code does not compile anymore : 
.../Humain.cpp:19: error: prototype for 'Humain::Humain(QString, int, int, int, int, Arme*)' does not match any in class 'Humain'
 Humain::Humain(QString nom, int physique, int mental, int vie, int psy, Arme* armeMainDroite) :

**Comment by msprosser** [comment]
Hello,
J'ai 5 erreurs de compilation, toi aussi ?
Moi il me dit que Humain n'a pas les attributs : nom, psy, mental, physique et vie (ceux qui viennent de la classe mère).
Regards

**Comment by xavierspr** [comment]
Solved with commit e5b4e12

**Comment by xavierspr** [comment]
My bad, still error in ctor Humain with multiple arguments. Cannot initialize inherited attributes from Personnage in initializer list of Humain.
https://stackoverflow.com/questions/3984215/c-initialization-of-inherited-field

**Comment by msprosser** [comment]
Compiles now :-)
